language: cpp

git:
  lfs_skip_smudge: true

before_install:
  - echo -e "machine github.com\n login $GITHUB_TOKEN" >> ~/.netrc
  - git lfs pull
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev
  - sudo apt-get install qt5-default qttools5-dev-tools
  - bash ci-before_install.sh

script:
  - qmake -project
  - qmake LudoMuseEditor.pro
  - make

