language: cpp


# works on Precise and Trusty
matrix:
  include:
    - os: osx
      osx_image: xcode9.2
      
    # - os: linux
    #   addons:
    #     apt:
    #       sources:
    #         - ubuntu-toolchain-r-test
    #       packages:
    #         - g++-7
    #         - chrpath
    #         - libglew-dev
    #         - binutils
    #         - binutils-dev
    #   env: COMPILER_NAME=gcc CXX=g++-7 CC=gcc-7


git:
  lfs_skip_smudge: true

sudo: required

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then travis_wait bash ./before_build_linux.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then travis_wait bash ./before_build_osx.sh; fi

script:
  # - echo "g++-7 ?"
  # - /usr/bin/g++-7 --version
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then travis_wait bash ./build_linux.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then travis_wait bash ./build_osx.sh; fi

