language: cpp

+os:
  - osx
  - linux

# works on Precise and Trusty
matrix:
  include:
    - os: osx
      osx_image: xcode9.2
      
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - chrpath
            - libglew-dev
            - binutils
            - binutils-dev
      env: COMPILER_NAME=gcc CXX=/usr/bin/g++-7 CC=/usr/bin/gcc-7


git:
  lfs_skip_smudge: true

sudo: required

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then travis_wait 50 bash ./before_build_linux.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then travis_wait 50 bash ./before_build_osx.sh; fi

script:
  # - echo "g++-7 ?"
  # - /usr/bin/g++-7 --version
  # - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then travis_wait 50 bash ./build_linux.sh; fi
  # - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then travis_wait 50 bash ./build_osx.sh; fi
  - cd libs/quazip/linux_build
  - rm *
  - /opt/qt58/bin/qmake ../quazip.pro CONFIG-=debug CONFIG+=release
  - make CXX=/usr/bin/g++-7
  - cd ../../../../
  - mkdir $HOME/LudoMuseEditor_build
  - cd $HOME/LudoMuseEditor_build
  - /opt/qt58/bin/qmake --version
  - /opt/qt58/bin/qmake CONFIG+=x86_64 CONFIG-=debug CONFIG+=release $TRAVIS_BUILD_DIR/LudoMuseEditor.pro
  - make CXX=/usr/bin/g++-7


  
before_deploy:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then travis_wait 50 bash ./before_deploy_linux.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then travis_wait 50 bash ./before_deploy_osx.sh; fi
  
deploy:
  - provider: script
    script: curl -u $UPLOAD_USER:$UPLOAD_PWD -T $HOME/LudoMuseEditor-$TRAVIS_OS_NAME.zip $UPLOAD_SERVER/LudoMuseEditor/LudoMuseEditor-$TRAVIS_OS_NAME-$TRAVIS_BUILD_NUMBER.zip
    skip_cleanup: true
    on:
      branch: master

  - provider: releases
    api_key:
      secure: $GITHUB_TOKEN
    file: "$HOME/LudoMuseEditor-linux.zip"
    skip_cleanup: true
    on:
      tags: true
    branch: master
