language: cpp


# works on Precise and Trusty
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - chrpath
            - libglew-dev
      env: COMPILER_NAME=gcc CXX=g++-7 CC=gcc-7

git:
  lfs_skip_smudge: true

sudo: required

before_install:
  - echo $PWD
  - travis_wait ./ci-before_install.sh $PWD
  - stat $PWD/../LudoMuse/cocos2d
  - echo -e "machine github.com\n login $GITHUB_TOKEN" >> ~/.netrc
    #  - git lfs pull
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo add-apt-repository --yes ppa:pyglfw/pyglfw
  - sudo apt-get update -qq
  - sudo apt-get install qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev
  - sudo apt-get install qt5-default qttools5-dev-tools
  - sudo apt-get install -y --no-install-recommends libglfw3-dev

script:
  # - echo "g++-7 ?"
  # - /usr/bin/g++-7 --version
  # - export GCC_PATH=$(which g++)
  # - sudo rm $GCC_PATH
  # - sudo ln -s $(dirname GCC_PATH)/g++-7 $GCC_PATH
  # - echo "Build will use g++ version :"
  # - g++ --version
  - qmake LudoMuseEditor.pro
  - make CC=/usr/bin/gcc-7 CXX=/usr/bin/g++-7

