language: cpp


# works on Precise and Trusty
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5

git:
  lfs_skip_smudge: true

before_install:
  - echo -e "machine github.com\n login $GITHUB_TOKEN" >> ~/.netrc
  - git lfs pull
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev
  - sudo apt-get install qt5-default qttools5-dev-tools
  - travis_wait bash ci-before_install.sh

script:
  - alias gcc=gcc-5
  - alias g++=gcc-5
  - echo "Build will use g++ version :"
  - g++ --version
  - qmake LudoMuseEditor.pro
  - make

