image: Visual Studio 2015

environment:
  matrix:
  - QT: C:\Qt\5.8\msvc2015
    PLATFORM: x86
    COMPILER: msvc
    VSVER: 14

clone_depth: 1

init:
  - set TAG_NAME=%APPVEYOR_REPO_TAG_NAME%

before_build:
  - git submodule update --init --recursive

build_script:
  - call "build_windows.cmd"

artifacts:
  - path: build\windows\msvc\x86\release\YourApp_$(appveyor_repo_tag_name)_windows_x86_portable.zip
    name: portable
  - path: installer\windows\x86\YourApp_$(appveyor_repo_tag_name)_windows_x86_installer.exe
    name: installer

deploy:
  - provider: GitHub
    tag: $(appveyor_repo_tag_name)
    release: $(appveyor_repo_tag_name)
    description: $(appveyor_repo_tag_name)
    auth_token:
      secure: sKI6y7bmEIh0RWxTFk+xBAAchjqJeVn3SX+yenB3N137XTmr0UIYEotJV0iIJnXu
    artifact: portable, installer
    draft: false
    prerelease: false
    force_update: true
    on:
      appveyor_repo_tag: true