image:
  - Visual Studio 2015
environment:
  PYTHON: "C:\\Python27"
  PYTHON_VERSION: "2.7.13"
  PYTHON_ARCH: "32"

  matrix:
  - QT: C:\Qt\5.8\msvc2015
    PLATFORM: x86
    COMPILER: msvc
    VSVER: 14

platform:
  - x86

configuration:
  - Release

clone_depth: 1

init:
  - set TAG_NAME=%APPVEYOR_REPO_TAG_NAME%
  - set GIT_LFS_SKIP_DOWNLOAD_ERRORS=1

before_build:
  - git submodule update --init --recursive

build_script:
  - call "build_windows.cmd"

artifacts:
  - path: $(APPVEYOR_BUILD_FOLDER)\..\LudoMuseEditorWin.zip
    name: portable
  # - path: installer\windows\x86\LudoMuseEditor$(appveyor_repo_tag_name)_windows_x86_installer.exe
  #   name: installer

deploy:
  - provider: GitHub
    tag: $(appveyor_repo_tag_name)
    release: $(appveyor_repo_tag_name)
    description: $(appveyor_repo_tag_name)
    auth_token:
      secure: $(GITHUB_TOKEN)
    artifact: portable, installer
    draft: false
    prerelease: false
    force_update: true
    on:
      appveyor_repo_tag: true


branches:
  except:
  - dev
